version: "3.8"
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: 'froomdb'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=froomdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'
    volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
