services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}'
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - .env