@startuml

component Backend {

    class User {
        - uuid: UUID
        - firstName: String
        - lastName: String
        - username: String
        - email : String
    }

    class Outfit {
        - uuid: UUID
        - name: String
        - items: Item[]
    }

    class Item {
        - uuid: UUID
        - color : String[]
        - category: Category
        - bodyPart: BodyPart
        - image: ByteArray
        - imageFormat: String
    }

    class Category {
        - uuid: UUID
        - name: String
        - bodyPart: BodyPart
        - index: int
    }

    enum BodyPart {
        TOP
        BOTTOM
        SHOES
        ACCESSORY
        UNKNOWN
    }

    User "1" -down- "0..*" Outfit : has
    User "1" -down- "0..*" Item : has
    Outfit "0..*" -down- "0..*" Item : contains
    Item "1" -right- "0..1" Category : categorized
    Item "1" -right- "0..1" BodyPart : associated
    Category -down-> BodyPart : has
}

@enduml