@startuml

title "Pomyślna rejestracja nowego użytkownika"

participant "Użytkownik" as User
participant "Przeglądarka" as Browser
participant "Serwer" as Server

User -> Browser: Otwórz stronę rejestracji
deactivate Server
Browser -> User: Pokaż stronę rejestracji
User -> Browser: Wypełnij formularz rejestracyjny i wyślij go
activate Server
Browser -> Server: Wyślij formularz rejestracyjny
Server -> Browser: Sprawdź formularz
alt poprawny
    Server -> Browser: Wyślij wiadomość o sukcesie
    Browser -> User: Pokaż wiadomość o sukcesie
else niepoprawny
    Server -> Browser: Wyślij wiadomość o błędzie
    Browser -> User: Pokaż wiadomość o błędzie
end
deactivate Server

@enduml
